# Generated by Django 4.0.10 on 2023-09-04 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('full_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Gasoline'), ('diesel', 'Diesel')], max_length=20)),
                ('seating_capacity', models.IntegerField()),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('sedan', 'Sedan'), ('coaster', 'Coaster'), ('grand_cabin', 'Grand Cabin')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleBookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected')], max_length=20)),
                ('reviewed', models.BooleanField(default=False)),
                ('rating', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_rides', to='userauth.profile')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drove_rides', to='userauth.profile')),
                ('dropoff_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropoffs', to='rentals.location')),
                ('pickup_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickups', to='rentals.location')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_rides', to='rentals.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.vehiclecategory'),
        ),
        migrations.CreateModel(
            name='StatusChangeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected')], max_length=20)),
                ('status_read', models.BooleanField(default=False)),
                ('booking_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='rentals.vehiclebookingrequest')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='userauth.profile')),
            ],
        ),
        migrations.CreateModel(
            name='FareRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare', models.IntegerField()),
                ('dropoff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropoff_fares', to='rentals.location')),
                ('pickup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_fares', to='rentals.location')),
            ],
        ),
    ]
