# Generated by Django 4.0.10 on 2023-09-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image_path',
            field=models.CharField(default='', max_length=255),
        ),
    ]
