# Generated by Django 4.0.10 on 2023-09-11 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='image_path',
        ),
    ]
