# Generated by Django 4.0.10 on 2023-09-03 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusChangeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_read', models.BooleanField(default=False)),
                ('booking_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='rentals.vehiclebookingrequest')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='userauth.profile')),
            ],
        ),
    ]
