# Generated by Django 4.0.10 on 2023-09-08 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclebookingrequest',
            name='reviewed',
        ),
        migrations.AlterField(
            model_name='statuschangenotification',
            name='notification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('read', 'Read')], default='delivered', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiclebookingrequest',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
