# Generated by Django 4.2.5 on 2023-09-27 09:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_date_attendance"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance",
            old_name="Subject",
            new_name="subject",
        ),
    ]
