# Generated by Django 4.0.10 on 2023-08-24 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclecategory',
            old_name='vehicle_category',
            new_name='category',
        ),
    ]
