# Generated by Django 4.0.10 on 2023-08-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='type',
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='fare_price_per_km',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='num_of_seats',
            field=models.IntegerField(default=0),
        ),
    ]
