# Generated by Django 4.0.10 on 2023-08-21 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_remove_car_type_car_category_car_fare_price_per_km_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=100)),
                ('dropoff_location', models.CharField(max_length=100)),
                ('car', models.OneToOneField(limit_choices_to={'is_available': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ride_request', to='rentals.car')),
                ('driver', models.OneToOneField(limit_choices_to={'is_available': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ride_request', to='rentals.driver')),
            ],
        ),
    ]
