# Generated by Django 4.0.10 on 2023-08-24 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_rename_vehicle_category_vehiclecategory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location_title',
            new_name='title',
        ),
    ]
