# Generated by Django 4.0.10 on 2023-08-24 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_rename_location_title_location_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='FareRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare', models.IntegerField()),
                ('dropoff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropoff_fares', to='rentals.location')),
                ('pickup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_fares', to='rentals.location')),
            ],
        ),
    ]
