# Generated by Django 4.0.10 on 2023-08-24 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_farerates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FareRates',
            new_name='FareRate',
        ),
    ]
