# Generated by Django 4.0.10 on 2023-08-24 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_rename_farerates_farerate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='fare_price',
        ),
    ]
